[package]
name = "arm_binary_tools"
version = "0.1.0"
edition = "2018"
author = "Graham Riches"
email = "Graham.Riches@live.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0.0"
string_utils = {path = "../string_utils"}